services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
      - "1143:1143"   # IMAP (IMPORTANT)
    environment:
      - MP_LISTEN_SMTP=0.0.0.0:1025
      - MP_LISTEN_HTTP=0.0.0.0:8025
      - MP_LISTEN_IMAP=0.0.0.0:1143
      - MP_IMAP_AUTH_ALLOW_INSECURE=true 